services:
  web:
    container_name: ${PROJECT_NAME}-web
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WORKDIR=${WORKDIR}
    command: flask run --host=0.0.0.0
    ports:
      - "${FLASK_PORT}:5000"
    volumes:
      - ${WORKDIR}:/home/app
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=${FLASK_ENV}
    depends_on:
      - db
  db:
    container_name: ${PROJECT_NAME}-db
    restart: "no"
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${DATADIR}/db:/var/lib/postgresql/data
      - ${DATADIR}/import:/home